service: 'TeamSync'
frameworkVersion: ">=1.32.0 < 2.0.0"
plugins:
  - 'serverless-pseudo-parameters'
  - 'serverless-plugin-optimize'
  - 'serverless-webpack'

custom:
  roleId: !Ref IAMLambdaRole
  slackApp:
    token: ${ssm:TeamSync-slackAppToken}
  messagesTableName: TeamSync-${self:provider.stage}-Messages
  teamsTableName: TeamSync-${self:provider.stage}-Teams
  questionsTableName: TeamSync-${self:provider.stage}-Questions
  profilesTableName: TeamSync-${self:provider.stage}-Profiles

provider:
  name: 'aws'
  runtime: 'nodejs10.x'
  region: ${opt:region, 'eu-west-2'}
  memorySize: '128'
  stage: ${opt:stage, 'dev'}

package:
  individually: 'true'
  exclude:
    - 'package.json'
    - 'package-lock.json'

functions:
  onAnswer:
    handler: 'handlers/onAnswer/onAnswer.lambda'
    description: 'TO DEFINE'
    role:
      Fn::GetAtt:
        - IAMLambdaRole
        - Arn
    events:
      - http:
          path: /answer
          method: post
    environment:
      SLACK_APP_TOKEN: ${self:custom.slackApp.token}
      MESSAGES_TABLE: ${self:custom.messagesTableName}
      TEAMS_TABLE: ${self:custom.teamsTableName}
      QUESTIONS_TABLE: ${self:custom.questionsTableName}
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}

  messageUser:
    handler: 'handlers/messageUser/messageUser.lambda'
    description: 'TO DEFINE'
    role:
      Fn::GetAtt:
        - IAMLambdaRole
        - Arn
    events:
      - http:
          path: /messageUser
          method: post
    environment:
      SLACK_APP_TOKEN: ${self:custom.slackApp.token}
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}

  subscribe:
    handler: 'handlers/subscribe/subscribe.lambda'
    description: 'TO DEFINE'
    role:
      Fn::GetAtt:
        - IAMLambdaRole
        - Arn
    events:
      - http:
          path: /subscribe
          method: post
    environment:
      SLACK_APP_TOKEN: ${self:custom.slackApp.token}
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}

#  Seeding
  seedQuestions:
    handler: 'seed/seedQuestions.lambda'
    description: 'Seeding questions to the table'
    role:
      Fn::GetAtt:
        - IAMLambdaRole
        - Arn
    environment:
      QUESTIONS_TABLE: ${self:custom.questionsTableName}
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}

resources:
  Resources:
    MessagesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.messagesTableName}
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
          - AttributeName: 'sessionId'
            AttributeType: 'S'
          - AttributeName: 'userId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        GlobalSecondaryIndexes:
          - IndexName: 'gsi_session'
            KeySchema:
              - AttributeName: 'sessionId'
                KeyType: 'HASH'
            Projection:
              ProjectionType: 'ALL'
          - IndexName: 'gsi_user'
            KeySchema:
              - AttributeName: 'userId'
                KeyType: 'HASH'
            Projection:
              ProjectionType: 'ALL'
        BillingMode: 'PAY_PER_REQUEST'
    TeamsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.teamsTableName}
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: 'PAY_PER_REQUEST'
    QuestionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.questionsTableName}
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: 'PAY_PER_REQUEST'
    ProfilesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.profilesTableName}
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: 'PAY_PER_REQUEST'

#   IAM
    IAMLambdaRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: 'Allow'
              Principal:
                Service:
                  - 'lambda.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
        RoleName: TeamSync_${self:provider.stage}_LambdaRole
