service: 'TeamSync'
frameworkVersion: ">=1.32.0 < 2.0.0"
plugins:
  - 'serverless-pseudo-parameters'
  - 'serverless-plugin-optimize'
  - 'serverless-webpack'

custom:
  roleId: !Ref IAMLambdaRole
  slackApp:
    token: ${ssm:TeamSync-slackAppToken}

provider:
  name: 'aws'
  runtime: 'nodejs10.x'
  region: ${opt:region, 'eu-west-2'}
  memorySize: '128'
  stage: ${opt:stage, 'dev'}

package:
  individually: 'true'
  exclude:
    - 'package.json'
    - 'package-lock.json'

functions:
  onAnswer:
    handler: 'handlers/onAnswer/onAnswer.lambda'
    description: 'TO DEFINE'
    role:
      Fn::GetAtt:
        - IAMLambdaRole
        - Arn
    events:
      - http:
          path: /answer
          method: post
    environment:
      SLACK_APP_TOKEN: ${self:custom.slackApp.token}
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}

resources:
  Resources:
    MessagesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: TeamSync-${self:provider.stage}-Messages
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
          - AttributeName: 'sessionId'
            AttributeType: 'S'
          - AttributeName: 'userId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        GlobalSecondaryIndexes:
          - IndexName: 'gsi_session'
            KeySchema:
              - AttributeName: 'sessionId'
                KeyType: 'HASH'
            Projection:
              ProjectionType: 'ALL'
          - IndexName: 'gsi_user'
            KeySchema:
              - AttributeName: 'userId'
                KeyType: 'HASH'
            Projection:
              ProjectionType: 'ALL'
        BillingMode: 'PAY_PER_REQUEST'

#   IAM
    IAMLambdaRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: 'Allow'
              Principal:
                Service:
                  - 'lambda.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
        RoleName: TeamSync_${self:provider.stage}_LambdaRole